In [ ]:
import requests
url='https://newsapi.org/v2/everything?q=ai&apiKey=da89a6771c3b491fb8d4dfe322a07a01'
params={
    "q": "ai",
    "language": "en",
    "sortBy": "publishedAt",
    "pageSize": 100,
    "page": 1,
    "apiKey": "da89a6771c3b491fb8d4dfe322a07a01"
}
response=requests.get(url,params=params)
print(response.json())

{'status': 'ok', 'totalResults': 69576, 'articles': [{'source': {'id': None, 'name': 'SiliconANGLE News'}, 'author': 'Emile Louw', 'title': 'Nutanix signals an infrastructure shift in AI — theCUBE’s .NEXT keynote analysis', 'description': 'As “move fast” collides headfirst with “don’t get breached,” the enterprise AI control plane has become the infrastructure question nobody can afford to leave unanswered. With\xa0shadow AI displacing shadow IT as the defining governance crisis of the decade, ent…', 'url': 'https://siliconangle.com/2026/04/08/nutanix-calls-shot-enterprise-ai-control-plane-nutanixnext/', 'urlToImage': 'https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2026/04/TheCUBEs-John-Furrier-and-Paul-Nashawaty.-—-Nutanix-.NEXT-2026.jpg', 'publishedAt': '2026-04-08T14:55:07Z', 'content': 'As “move fast” collides headfirst with “don’t get breached,” the enterprise AI control plane has become the infrastructure question nobody can afford to leave unanswered.\r\nWith\xa0shadow AI displacing s… [+4977 chars]'}, {'source': {'id': 'fortune', 'name': 'Fortune'}, 'author': 'Catherina Gioino', 'title': 'China is going after fake expert influencers, and the FTC’s new five-year plan seems to lay the same groundwork', 'description': 'China issued new regulation banning people without proper credentials from offering any tips related to health, finance or education online. The FTC just released a similar playbook.', 'url': 'https://fortune.com/2026/04/08/china-fake-expert-influencers-ftc-five-year-plan/', 'urlToImage': 'https://fortune.com/img-assets/wp-content/uploads/2026/04/GettyImages-1320999349-e1775595357149.jpg?resize=1200,600', 'publishedAt': '2026-04-08T14:53:25Z', 'content': 'Do you get health tips on social media? Maybe finance help or some self-education? Have you seen the fictional Oxford Study about Asian women and white men, or the hashtags related to ADHD or sinus t… [+4343 chars]'}, {'source': {'id': None, 'name': 'Abduzeedo.com'}, 'author': 'alex', 'title': 'Faybl Brand Identity: Fubo Studio Designs AI for Financial Advisers', 'description': 'Faybl Brand Identity: Fubo Studio Designs AI for Financial Advisers\n\n \n\n\n alex\n April 08, 2026\n\n\n Fubo Studio crafts the Faybl brand identity around node symbols and a trust palette, positioning AI for financial advisers as human connections at scale.\nThe fin…', 'url': 'https://abduzeedo.com/node/89265', 'urlToImage': None, 'publishedAt': '2026-04-08T14:53:00Z', 'content': 'Fubo Studio crafts the Faybl brand identity around node symbols and a trust palette, positioning AI for financial advisers as human connections at scale.\r\nThe financial services industry faces a quie… [+1709 chars]'}, {'source': {'id': None, 'name': 'POLITICO.eu'}, 'author': 'Joseph Bambridge', 'title': 'OpenAI puts ‘Stargate UK’ on hold in blow to Britain’s AI ambitions', 'description': "OpenAI said issues including the U.K.'s copyright rules and energy prices affect its investment decisions.", 'url': 'https://www.politico.eu/article/openai-stargate-uk-pause-setback-britain-ai-ambitions/', 'urlToImage': 'https://www.politico.eu/cdn-cgi/image/width=1200,height=630,fit=crop,quality=80,onerror=redirect/wp-content/uploads/2026/04/08/open-ai-scaled.jpg', 'publishedAt': '2026-04-08T14:52:33Z', 'content': 'The sites included Cobalt Park, part of a government-designated AI Growth Zone in the North East of England.\r\nHowever, OpenAI has yet to take up the chips, with a spokesperson telling POLITICO that w… [+1267 chars]'}, {'source': {'id': None, 'name': 'TelecomTV'}, 'author': 'TelecomTV Staff', 'title': 'What’s up with… Gamma Comms, Globe, DT', 'description': 'Gamma Comms confirms takeover talksGlobe joins Candle subsea consortiumDeutsche Telekom adds Starlink to its B2B mix', 'url': 'https://www.telecomtv.com/content/digital-platforms-services/what-s-up-with-gamma-comms-globe-dt-55260/', 'urlToImage': 'https://assets.telecomtv.com/assets/telecomtv/gamma-comms-source-gamma-comms-22259.jpeg?w=1200', 'publishedAt': '2026-04-08T14:51:26Z', 'content': 'In today’s industry news roundup: UK’s Gamma’s share price leaps as it confirms it’s in M&amp;A talks with multiple potential bidders; Globe to light up Candle network in the Philippines; DT adds Sta… [+4880 chars]'}, {'source': {'id': None, 'name': 'Windows Central'}, 'author': 'c.cale.hunt@gmail.com (Cale Hunt) , Cale Hunt', 'title': '"Raptor Lake will continue to be abundantly available": Intel exec makes a case for its older chips as RAM prices soar, but are they actually worth buying in 2026?', 'description': 'Intel\'s aging Raptor Lake desktop CPUs are "not going anywhere," according to an Intel exec, as RAM prices soar and PC gamers search for DDR4 alternatives. Are these chips worth buying in 2026? Let\'s explore.', 'url': 'https://www.windowscentral.com/hardware/intel/intel-raptor-lake-ddr4-cpu-benefits-pc-gaming', 'urlToImage': 'https://cdn.mos.cms.futurecdn.net/MqpiK7fwgQ9ohFHvKZeEUH-1256-80.jpg', 'publishedAt': '2026-04-08T14:51:06Z', 'content': "Perhaps unsurprisingly, due to the state of the PC gaming hardware market, Intel has clarified that it doesn't have plans to retire production of its 13th and 14th Gen Core processors.\r\nIn an intervi… [+3320 chars]"}, {'source': {'id': None, 'name': 'Pypi.org'}, 'author': None, 'title': 'encypher-ai 3.1.0', 'description': 'Embed invisible metadata in AI-generated text using zero-width characters.', 'url': 'https://pypi.org/project/encypher-ai/3.1.0/', 'urlToImage': None, 'publishedAt': '2026-04-08T14:50:06Z', 'content': 'A required part of this site couldnt load. This may be due to a browser\r\n extension, network issues, or browser settings. Please check your\r\n connection, disable any ad blockers, or try using a diffe… [+12 chars]'}, {'source': {'id': None, 'name': 'Logisticsviewpoints.com'}, 'author': 'Jim Frazer', 'title': 'Decision Latency: The Hidden Cost in Modern Supply Chains', 'description': 'In modern supply chains, disruption does not always begin with a weather event, a port closure, or a supplier failure. It often begins inside the decision cycle itself, where fragmented data, unclear ownership, and slow escalation turn manageable issues into …', 'url': 'https://logisticsviewpoints.com/2026/04/08/decision-latency-the-hidden-cost-in-modern-supply-chains/', 'urlToImage': 'https://logisticsviewpoints.com/wp-content/uploads/2026/04/tungart7-worker-8941865-scaled.jpg', 'publishedAt': '2026-04-08T14:49:28Z', 'content': 'In modern supply chains, disruption does not always begin with a weather event, a port closure, or a supplier failure. It often begins inside the decision cycle itself, where fragmented data, unclear… [+10135 chars]'}, {'source': {'id': None, 'name': 'Pypi.org'}, 'author': None, 'title': 'csctracker-ai-core 26.15.2', 'description': 'A robust library to integrate Google Gemini AI with API key rotation and ClickHouse telemetry.', 'url': 'https://pypi.org/project/csctracker-ai-core/26.15.2/', 'urlToImage': None, 'publishedAt': '2026-04-08T14:49:18Z', 'content': 'A required part of this site couldnt load. This may be due to a browser\r\n extension, network issues, or browser settings. Please check your\r\n connection, disable any ad blockers, or try using a diffe… [+12 chars]'}, {'source': {'id': None, 'name': "Tom's Hardware UK"}, 'author': 'ashilov@gmail.com (Anton Shilov) , Anton Shilov', 'title': "Bain Capital's data center unit removes disgraced tenant suspected of smuggling Nvidia GPUs to China — Megaspeed previously alleged to have spent roughly $2 billion on AI processors for illicit distribution", 'description': 'Megaspeed gets final nail in its coffin after Bridge Data Centers cancels its tenancy and replaces it with U.S.-based Zenplayer.', 'url': 'https://www.tomshardware.com/tech-industry/artificial-intelligence/bain-capitals-data-center-unit-removes-disgraced-tenant-suspected-of-smuggling-nvidia-gpus-to-china-megaspeed-previously-alleged-to-have-spent-roughly-usd2-billion-on-ai-processors-for-illicit-distribution', 'urlToImage': 'https://cdn.mos.cms.futurecdn.net/ibEpXbFzhNegj42rkqPzgZ-1920-80.jpg', 'publishedAt': '2026-04-08T14:47:54Z', 'content': "Bain Capital's Bridge Data Centers (BDC) has terminated its contract with Megaspeed International at its Malaysian site after the U.S. government began a probe into whether Megaspeed smuggled restric… [+4191 chars]"}, {'source': {'id': None, 'name': 'Pypi.org'}, 'author': None, 'title': 'clawed 4.8.2026.3', 'description': 'Your AI co-teacher. Generate lessons, games, slides, and assessments from your terminal. Learns your teaching voice, aligns to your state standards, and works with any LLM provider.', 'url': 'https://pypi.org/project/clawed/4.8.2026.3/', 'urlToImage': None, 'publishedAt': '2026-04-08T14:46:54Z', 'content': 'A required part of this site couldnt load. This may be due to a browser\r\n extension, network issues, or browser settings. Please check your\r\n connection, disable any ad blockers, or try using a diffe… [+12 chars]'}, {'source': {'id': None, 'name': 'Pypi.org'}, 'author': 'kobie@pop.co.za', 'title': 'ai-iq 5.8.0', 'description': 'Give your AI long-term memory in 1 command. SQLite-based, no setup, no servers.', 'url': 'https://pypi.org/project/ai-iq/5.8.0/', 'urlToImage': None, 'publishedAt': '2026-04-08T14:46:19Z', 'content': 'A required part of this site couldnt load. This may be due to a browser\r\n extension, network issues, or browser settings. Please check your\r\n connection, disable any ad blockers, or try using a diffe… [+12 chars]'}, {'source': {'id': None, 'name': '404media.co'}, 'author': 'Joseph Cox', 'title': 'Microsoft Abruptly Terminates VeraCrypt Account, Halting Windows Updates', 'description': 'Updates to VeraCrypt, a popular and long-running piece of encryption, are now thrown into doubt because of a seemingly unexplained Microsoft decision.', 'url': 'https://www.404media.co/microsoft-abruptly-terminates-veracrypt-account-halting-windows-updates/', 'urlToImage': 'https://www.404media.co/content/images/size/w1200/2026/04/simon-ray-TICJQELFmg4-unsplash.jpg', 'publishedAt': '2026-04-08T14:46:15Z', 'content': 'Microsoft has terminated an account associated with VeraCrypt, a popular and long-running piece of encryption software, throwing future Windows updates of the tool into doubt, VeraCrypts developer to… [+3025 chars]'}, {'source': {'id': None, 'name': 'Yahoo Entertainment'}, 'author': 'David Okoya', 'title': "Bitcoin Over $100K 'Totally Reasonable In One Year's Time,' VanEck Digital Assets Research Chief Says", 'description': 'Bitcoin could return above $100,000 in the short- to medium-term horizon, according to VanEck Head of Digital Assets Research Matthew Sigel. "I think that’s ...', 'url': 'https://finance.yahoo.com/markets/crypto/articles/bitcoin-over-100k-totally-reasonable-144607164.html', 'urlToImage': 'https://s.yimg.com/os/en/benzinga_79/b3d284cabf6fcc0be3c87622145e8327', 'publishedAt': '2026-04-08T14:46:07Z', 'content': 'Benzinga and Yahoo Finance LLC may earn commission or revenue on some items through the links below.\r\nBitcoin could return above $100,000 in the short- to medium-term horizon, according to VanEck Hea… [+11119 chars]'}, {'source': {'id': None, 'name': 'GlobeNewswire'}, 'author': 'D S Simon', 'title': 'OpenAI and Meaghan B Murphy Discuss How Families Are Using ChatGPT Safely and with Confidence with YourUpdateTV', 'description': 'Nationwide media tour conducted by OpenAI, produced by D S Simon Media, on the topic of “What Every Parent Should Know About AI Safety.” Nationwide media tour conducted by OpenAI, produced by D S Simon Media, on the topic of “What Every Parent Should Know Abo…', 'url': 'https://www.globenewswire.com/news-release/2026/04/08/3270320/0/en/OpenAI-and-Meaghan-B-Murphy-Discuss-How-Families-Are-Using-ChatGPT-Safely-and-with-Confidence-with-YourUpdateTV.html', 'urlToImage': 'https://ml.globenewswire.com/Resource/Download/5115f449-412d-4a05-bbcb-add09b3f2838', 'publishedAt': '2026-04-08T14:46:00Z', 'content': 'NEW YORK, April 08, 2026 (GLOBE NEWSWIRE) -- \r\nArtificial intelligence is quickly becoming part of everyday teen life. Tools like ChatGPT, developed by OpenAI, are now used for everything from school… [+1870 chars]'}, {'source': {'id': None, 'name': 'The Conversation Africa'}, 'author': 'Debra Ferreday, Senior Lecturer in Sociology, Lancaster University', 'title': 'The Testaments: female friendship fuels resistance in this Handmaid’s Tale sequel', 'description': 'The Testaments has to resolve the plot dilemmas established in The Handmaid’s Tale.', 'url': 'https://theconversation.com/the-testaments-female-friendship-fuels-resistance-in-this-handmaids-tale-sequel-280062', 'urlToImage': 'https://images.theconversation.com/files/728325/original/file-20260407-71-6lu7rm.jpg?ixlib=rb-4.1.0&rect=400%2C0%2C2160%2C1080&q=45&auto=format&w=1356&h=668&fit=crop', 'publishedAt': '2026-04-08T14:45:45Z', 'content': 'The Testaments, now streaming on Disney+, has big shoes to fill. It arrives in a post-MeToo media landscape still shaped by the seismic impact of Margaret Atwood’s previous adaptation, The Handmaid’s… [+6107 chars]'}, {'source': {'id': None, 'name': 'Livedoor.biz'}, 'author': 'michaelsan', 'title': '地上波で美女のマ●毛を集めて枕を作る企画を放送してしまい炎上', 'description': '1 ：それでも動く名無し：2026/04/07(火) 19:24:03.22 ID:7BY6o6AZ0.nethttps://pbs.twimg.com/media/HFBqyLKbYAAwc_N.jpghttps://pbs.twimg.com/media/HFBq4R5a4AARQwT.jpghttps://pbs.twimg.com/media/HFBq1qTaUAAQSEd.jpghttps://pbs.twimg.com/media/HFBq21fbQAAMx9w.jpg', 'url': 'https://michaelsan.livedoor.biz/archives/52067003.html', 'urlToImage': 'https://livedoor.blogimg.jp/michaelsan/imgs/c/4/c4149dc6.jpg', 'publishedAt': '2026-04-08T14:45:43Z', 'content': '9 2026/04/07() 19:25:25.12 ID:r2LXnoOe0.net\r\n14 2026/04/07() 19:26:44.34 ID:+fRxoqps0.net\r\n\xa021 2026/04/07() 19:28:49.34 ID:jvLUokjH0.net\r\n24 2026/04/07() 19:29:51.53 ID:HyJxcoPZ0.net\r\n\xa031 2026/04/07(… [+959 chars]'}, {'source': {'id': None, 'name': 'Abduzeedo.com'}, 'author': 'alex', 'title': 'CSS Studio: Design Visually, Ship Code with AI', 'description': 'CSS Studio: Design Visually, Ship Code with AI\n\n \n\n\n alex\n April 08, 2026\n\n\n CSS Studio is a browser-based CSS design tool that lets designers edit styles, layout, and content visually while an AI agent writes every change directly into source code.\nThe gap b…', 'url': 'https://abduzeedo.com/node/89267', 'urlToImage': None, 'publishedAt': '2026-04-08T14:44:15Z', 'content': 'CSS Studio is a browser-based CSS design tool that lets designers edit styles, layout, and content visually while an AI agent writes every change directly into source code.\r\nThe gap between visual de… [+1966 chars]'}, {'source': {'id': None, 'name': 'Theregister.com'}, 'author': 'Tim Anderson', 'title': 'Microsoft calls time on ASP.NET Core 2.3 on .NET Framework', 'description': 'Tangled tale nears end as Redmond classifies it as a tool, not a library\nMicrosoft has set an end-of-support date of April 7, 2027, for ASP.NET Core 2.3, the only supported version on .NET Framework, even though .NET Framework (and the original ASP.NET) will …', 'url': 'https://www.theregister.com/2026/04/08/aspnet_net_framework/', 'urlToImage': 'https://regmedia.co.uk/2018/08/03/shutterstock_road_block_no_access.jpg', 'publishedAt': '2026-04-08T14:43:32Z', 'content': 'Microsoft has set an end-of-support date of April 7, 2027, for ASP.NET Core 2.3, the only supported version on .NET Framework, even though .NET Framework (and the original ASP.NET) will continue to b… [+3732 chars]'}, {'source': {'id': None, 'name': 'Pypi.org'}, 'author': 'guipe@sovyx.ai', 'title': 'sovyx 0.5.10', 'description': 'Sovereign Minds Engine — Persistent AI companion with real memory', 'url': 'https://pypi.org/project/sovyx/0.5.10/', 'urlToImage': None, 'publishedAt': '2026-04-08T14:43:24Z', 'content': 'A required part of this site couldnt load. This may be due to a browser\r\n extension, network issues, or browser settings. Please check your\r\n connection, disable any ad blockers, or try using a diffe… [+12 chars]'}, {'source': {'id': None, 'name': 'Freerepublic.com'}, 'author': 'AMAC', 'title': 'Trump Administration Pushes for Companies to Bring Call Centers Back to America', 'description': 'The frustrating experience of trying to speak with customer support only to be transferred to a foreign call center and connected with someone who barely speaks English could soon be coming to an end thanks to the Trump administration. Last week, the Federal …', 'url': 'https://freerepublic.com/focus/f-news/4374108/posts', 'urlToImage': None, 'publishedAt': '2026-04-08T14:43:14Z', 'content': 'Skip to comments.\r\nTrump Administration Pushes for Companies to Bring Call Centers Back to AmericaAMAC ^\r\n | April 2, 2026\r\n | Alan Jamison\r\nPosted on 04/08/2026 7:43:14 AM PDT by re_tail20\r\nThe frus… [+4344 chars]'}, {'source': {'id': None, 'name': 'Cult of Mac'}, 'author': 'Ed Hardy', 'title': 'Biggest problem with the MacBook Neo? It’s too popular!', 'description': 'Apple has a problem that other companies can only dream of. It might completely sell out of the MacBook Neo.\n(via Cult of Mac - Your source for the latest Apple news, rumors, analysis, reviews, how-tos and deals.)', 'url': 'https://www.cultofmac.com/news/macbook-neo-sold-out-2', 'urlToImage': 'https://www.cultofmac.com/wp-content/uploads/2026/04/MacBook-Neo-sold-out.jpg.webp', 'publishedAt': '2026-04-08T14:42:51Z', 'content': 'Apple has a problem with the MacBook Neo that other companies can only dream of. AI image: Apple/Gemini/Cult of Mac\r\nWant a MacBook Neo? Better order it soon. It’s possible Apple will sell out of the… [+4145 chars]'}, {'source': {'id': None, 'name': 'Frontiersin.org'}, 'author': 'Jun Zhu', 'title': 'Frontiers | State of health estimation method for lithium-ion battery packs based on SSPC-temperature features and CNN-KAN-BiGRU model', 'description': 'As the main power source of new energy vehicles, the accurate estimation of the health status of lithium-ion battery packs is crucial for ensuring the safe o...', 'url': 'https://www.frontiersin.org/journals/energy-research/articles/10.3389/fenrg.2026.1775546/full', 'urlToImage': 'https://d2csxpduxe849s.cloudfront.net/media/E32629C6-9347-4F84-81FEAEF7BFA342B3/F7B43C93-68F6-4D87-A0D64BC7C5E714F1/CACA30D1-0EF2-4234-8E10F40FCF9E026F/WebsiteWebP_XL-FENRG_Main Visual_Green_Website.webp', 'publishedAt': '2026-04-08T14:41:56Z', 'content': 'Abstract\r\nAs the main power source of new energy vehicles, the accurate estimation of the health status of lithium-ion battery packs is crucial for ensuring the safe operation of the battery system. … [+48479 chars]'}, {'source': {'id': None, 'name': 'Pypi.org'}, 'author': 'hello@daisytuner.com', 'title': 'docc-ai 0.0.7', 'description': 'Python bindings and MLIR conversion for JIT compiling PyTorch models to SDFGs.', 'url': 'https://pypi.org/project/docc-ai/', 'urlToImage': 'https://pypi.org/static/images/twitter.abaf4b19.webp', 'publishedAt': '2026-04-08T14:41:54Z', 'content': 'The MLIR module contains a dialect and translation of core MLIR dialects to SDFGs.\r\n<ul><li>SDFG Dialect: A dialect to represent SDFGs in MLIR.</li><li>Conversion: Conversion passes to convert core d… [+1018 chars]'}, {'source': {'id': None, 'name': 'Abcnews.com'}, 'author': 'ABC News', 'title': 'WATCH: The impact of space travel on the human body', 'description': 'Space medicine researcher Dr. Farhan Asrar discusses the health impact the historic mission will have on the Artemis II crew.', 'url': 'https://abcnews.com/video/131839305/', 'urlToImage': 'https://i.abcnewsfe.com/a/36cdd86b-00fc-4f83-bcd2-e23ce4400600/260408_abcnl_9a_artemis2_asrar_hpMain_16x9.jpg?w=992', 'publishedAt': '2026-04-08T14:40:55Z', 'content': "<ul><li>Trump achieved 'decisive military victory' in Iran, Hegseth says\r\n</li><li>What new images from Artemis II could tell us about the moon\r\n</li><li>After SCOTUS presidential i

In [ ]:
articles=response.json()['articles']
for article in articles:
    print(article['title'])

Nutanix signals an infrastructure shift in AI — theCUBE’s .NEXT keynote analysis
China is going after fake expert influencers, and the FTC’s new five-year plan seems to lay the same groundwork
Faybl Brand Identity: Fubo Studio Designs AI for Financial Advisers
OpenAI puts ‘Stargate UK’ on hold in blow to Britain’s AI ambitions
What’s up with… Gamma Comms, Globe, DT
"Raptor Lake will continue to be abundantly available": Intel exec makes a case for its older chips as RAM prices soar, but are they actually worth buying in 2026?
encypher-ai 3.1.0
Decision Latency: The Hidden Cost in Modern Supply Chains
csctracker-ai-core 26.15.2
Bain Capital's data center unit removes disgraced tenant suspected of smuggling Nvidia GPUs to China — Megaspeed previously alleged to have spent roughly $2 billion on AI processors for illicit distribution
clawed 4.8.2026.3
ai-iq 5.8.0
Microsoft Abruptly Terminates VeraCrypt Account, Halting Windows Updates
Bitcoin Over $100K 'Totally Reasonable In One Year's Time,' VanEck Digital Assets Research Chief Says
OpenAI and Meaghan B Murphy Discuss How Families Are Using ChatGPT Safely and with Confidence with YourUpdateTV
The Testaments: female friendship fuels resistance in this Handmaid’s Tale sequel
地上波で美女のマ●毛を集めて枕を作る企画を放送してしまい炎上
CSS Studio: Design Visually, Ship Code with AI
Microsoft calls time on ASP.NET Core 2.3 on .NET Framework
sovyx 0.5.10
Trump Administration Pushes for Companies to Bring Call Centers Back to America
Biggest problem with the MacBook Neo? It’s too popular!
Frontiers | State of health estimation method for lithium-ion battery packs based on SSPC-temperature features and CNN-KAN-BiGRU model
docc-ai 0.0.7
WATCH: The impact of space travel on the human body
Why is the US stock market today Dow S&P 500 Nasdaq rallying so sharply? Dow Jones jumps 1200 points while S&P 500 and Nasdaq surge over 2% on ceasefire optimism
Energous (WATT) Gained from a Dilutive Capital Raise by Management
warden-ai 1.5.1
Deloitte launches quantum tech facility at IIT Bombay
GMH Hotels: Is $7 Billion in Hotel Points a Problem?
csctracker-ai-core 26.15.1
Show HN: Hoeren – Local-only meeting transcription and voice dictation
zenml 0.94.2
The Miniature Wife was an exercise in visual trickery
hana-ai 1.1.26040800
codereviewbuddy 0.37.0
Anthropic Just Handed Apache $1.5M to Secure the Open Source Stack AI Depends On
How Ford Is Reinventing Itself as an AI Infrastructure Play After Its EV Stumble
Kingdom Capital Advisors’ Investment Thesis for Alliance Entertainment Holding Corporation (AENT)
agentmark-pydantic-ai-v0 0.1.1
E-retail set to cross $170 billion by 2030; q-comm, Gen Z drive next wave: Report
Show HN: Go-Bt: Minimalist Behavior Trees for Go
Cybersecurity Stocks Climb Amid Anthropic's Project Glasswing Launch - Investor's Business Daily
Nectar Social and Reddit Announce Strategic Data Partnership
orbis-sdk added to PyPI
peek-mcp 0.2.2
Calero Launches Calero ConnectIQ
Electronic Design Automation (EDA) Market Size to Hit $42.85 Billion by 2035 | Research by SNS Insider
Humanoid Robot Market Set for Rapid Expansion: Size, Share & Trends (2025–2030)
Conference organising in 2026 - QuirksBlog
MEXC targets EU MiCA compliance as new CEO takes helm
Show HN: Real-time deepfake in the browser, no GPU needed
Tom Holland opens up on additional shooting for Spider-Man Brand New Day, says it’s ‘icing on the cake’
UMB Financial Rated New Outperform: The Under-the-Radar Regional Bank Wall Street Just Discovered
shoal-cli 0.40.0
mirdan 2.0.3
Morgan Stanley has a stark message for investors in Apple
x-agent-kit 0.3.8
research-mentor 1.0.3
Latin America MNO (Mobile Network Operators) Directory 2026-2027: Key Insights to Collaborate with 135+ Operators Across 46 Countries
Nexon ‘Reassigns’ The First Berserker: Khazan Team After it Failed to Meet Commercial Expectations
solace-agent-mesh 1.18.31
Citi Remains Bullish on Taiwan Semiconductor (TSM) Amid Growing Demand for AI-Driven Chips
Goldman Sachs Cautious on QUALCOMM (QCOM) Amid Key Customer Losses
“I have a feeling that everyone likes using AI...
Analysts See Over 100% Upside in IREN (IREN) Amid Growing Demand for AI-Linked Compute Infrastructure
Is Microsoft (MSFT) One of the Hedge Fund Favorites with Strong Setup in 2026?
Micron Technology (MU), One of the Hedge Fund Favorites with Strong Setup in 2026
catai-linux 0.1.2
agent-coordinator 1.0.0rc2
paygent-sdk 4.7.0
British cryptographer Adam Back is the secret creator of Bitcoin, claims new report — Back refutes investigation, says parallels to Satoshi are just a coincidence
ai-automated-pipeline 0.1.0
ai-automated-pipeline added to PyPI
clawed 4.8.2026.2
signet-auth 0.5.0
videosdk-plugins-speechify 1.0.5
Pixel Watch 4 turns into the best Galaxy Watch 8 alternative after a lovely discount
jarvis-ai-assistant 3.0.16
Cloudflare and ETH Zurich Outline Approaches for AI-Driven Cache Optimization
videosdk-plugins-rime 1.0.5
ai-software-factory 1.0.3
videosdk-plugins-neuphonic 1.0.5
videosdk-plugins-lmnt 1.0.5
videosdk-plugins-humeai 1.0.5
Middle East MNO (Mobile Network Operators) Directory 2026-2027: 42+ Operators Across Bahrain, Iran, Iraq, Israel, Jordan, Kuwait, Lebanon, Oman, Palestine, Qatar, Saudi Arabia, Syria, UAE, Yemen
mcp-seedance 2026.4.8.1
mcp-seedream-pro 2026.4.8.1
mcp-flux-pro 2026.4.8.1
LPL Financial Gets a UBS Buy Rating: Wall Street Sees $380 for This Wealth Management Play
Equinix launches IBX Data Centre in Mumbai
Modus secures $85m to advance AI-driven audit platform
North America MNO (Mobile Network Operators) Directory 2026-2027: Access 19+ Operators Across Canada, Greenland, Guam, USA
Americans Lost Record $11.4 Billion to Crypto Scams in 2025, FBI Report Reveals
Show HN: Embenx – agentic memory layer for AI agents
Supermicro launches probe after staff charged with China export violations
Omnia Sol, glitch artist and cinematic raver
As IBS 2026 Approaches, LEPAS Unfolds Its “Elegance Moves the World” Trilogy
Mobile Virtual Network Operator (MVNO) Market Report 2026-2030: Virtual Service Provider Actions, Corporate Strategies, and Emerging Technologies - Innovations in ESIMs, IoT, and Embedded Banking
INVESTOR ALERT: Class Action Lawsuit Filed on Behalf of  Upstart Holdings, Inc.(UPST) Investors – Holzer & Holzer, LLC Encourages Investors With Significant Losses to Contact the Firm

In [ ]:
import pandas as pd
df=pd.DataFrame(articles)
df

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'SiliconANGLE News'}",Emile Louw,Nutanix signals an infrastructure shift in AI ...,As “move fast” collides headfirst with “don’t ...,https://siliconangle.com/2026/04/08/nutanix-ca...,https://d15shllkswkct0.cloudfront.net/wp-conte...,2026-04-08T14:55:07Z,As “move fast” collides headfirst with “don’t ...
1,"{'id': 'fortune', 'name': 'Fortune'}",Catherina Gioino,"China is going after fake expert influencers, ...",China issued new regulation banning people wit...,https://fortune.com/2026/04/08/china-fake-expe...,https://fortune.com/img-assets/wp-content/uplo...,2026-04-08T14:53:25Z,Do you get health tips on social media? Maybe ...
2,"{'id': None, 'name': 'Abduzeedo.com'}",alex,Faybl Brand Identity: Fubo Studio Designs AI f...,Faybl Brand Identity: Fubo Studio Designs AI f...,https://abduzeedo.com/node/89265,None,2026-04-08T14:53:00Z,Fubo Studio crafts the Faybl brand identity ar...
3,"{'id': None, 'name': 'POLITICO.eu'}",Joseph Bambridge,OpenAI puts ‘Stargate UK’ on hold in blow to B...,OpenAI said issues including the U.K.'s copyri...,https://www.politico.eu/article/openai-stargat...,https://www.politico.eu/cdn-cgi/image/width=12...,2026-04-08T14:52:33Z,"The sites included Cobalt Park, part of a gove..."
4,"{'id': None, 'name': 'TelecomTV'}",TelecomTV Staff,"What’s up with… Gamma Comms, Globe, DT",Gamma Comms confirms takeover talksGlobe joins...,https://www.telecomtv.com/content/digital-plat...,https://assets.telecomtv.com/assets/telecomtv/...,2026-04-08T14:51:26Z,In today’s industry news roundup: UK’s Gamma’s...
...,...,...,...,...,...,...,...,...
95,"{'id': None, 'name': 'Theregister.com'}",Dan Robinson,Supermicro launches probe after staff charged ...,Board-led inquiry follows indictment of two em...,https://www.theregister.com/2026/04/08/supermi...,https://regmedia.co.uk/2026/04/08/shutterstock...,2026-04-08T14:15:35Z,Supermicro has launched an independent investi...
96,"{'id': None, 'name': 'Chicago Reader'}",Micco Caporale,"Omnia Sol, glitch artist and cinematic raver","Syd Ross resists tidy categorization, but as a...",http://chicagoreader.com/music/chicagoans-of-n...,https://chicagoreader.com/wp-content/uploads/2...,2026-04-08T14:15:34Z,Omnia Sol performs with Chicago A/V collective...
97,"{'id': 'financial-post', 'name': 'Financial Po...",GlobeNewswire,"As IBS 2026 Approaches, LEPAS Unfolds Its “Ele...","WUHU, China, April 08, 2026 (GLOBE NEWSWIRE) —...",https://financialpost.com/globe-newswire/as-ib...,https://smartcdn.gprod.postmedia.digital/finan...,2026-04-08T14:15:27Z,"WUHU, China, April 08, 2026 (GLOBE NEWSWIRE) T..."
98,"{'id': None, 'name': 'GlobeNewswire'}",Research and Markets,Mobile Virtual Network Operator (MVNO) Market ...,Emerging MVNO market opportunities include lev...,https://www.globenewswire.com/news-release/202...,https://ml.globenewswire.com/Resource/Download...,2026-04-08T14:15:00Z,"Dublin, April 08, 2026 (GLOBE NEWSWIRE) -- The..."
99,"{'id': None, 'name': 'GlobeNewswire'}",Holzer & Holzer,INVESTOR ALERT: Class Action Lawsuit Filed on ...,"ATLANTA, April 08, 2026 (GLOBE NEWSWIRE) -- A ...",https://www.globenewswire.com/news-release/202...,https://ml.globenewswire.com/Resource/Download...,2026-04-08T14:14:00Z,"ATLANTA, April 08, 2026 (GLOBE NEWSWIRE) -- A ..."

In [ ]:
df = df[["title","description","content","publishedAt","author"]].copy()
df.head(50)

,title,description,content,publishedAt,author
0,Nutanix signals an infrastructure shift in AI ...,As “move fast” collides headfirst with “don’t ...,As “move fast” collides headfirst with “don’t ...,2026-04-08T14:55:07Z,Emile Louw
1,"China is going after fake expert influencers, ...",China issued new regulation banning people wit...,Do you get health tips on social media? Maybe ...,2026-04-08T14:53:25Z,Catherina Gioino
2,Faybl Brand Identity: Fubo Studio Designs AI f...,Faybl Brand Identity: Fubo Studio Designs AI f...,Fubo Studio crafts the Faybl brand identity ar...,2026-04-08T14:53:00Z,alex
3,OpenAI puts ‘Stargate UK’ on hold in blow to B...,OpenAI said issues including the U.K.'s copyri...,"The sites included Cobalt Park, part of a gove...",2026-04-08T14:52:33Z,Joseph Bambridge
4,"What’s up with… Gamma Comms, Globe, DT",Gamma Comms confirms takeover talksGlobe joins...,In today’s industry news roundup: UK’s Gamma’s...,2026-04-08T14:51:26Z,TelecomTV Staff
5,"""Raptor Lake will continue to be abundantly av...","Intel's aging Raptor Lake desktop CPUs are ""no...","Perhaps unsurprisingly, due to the state of th...",2026-04-08T14:51:06Z,"c.cale.hunt@gmail.com (Cale Hunt) , Cale Hunt"
6,encypher-ai 3.1.0,Embed invisible metadata in AI-generated text ...,A required part of this site couldnt load. Thi...,2026-04-08T14:50:06Z,None
7,Decision Latency: The Hidden Cost in Modern Su...,"In modern supply chains, disruption does not a...","In modern supply chains, disruption does not a...",2026-04-08T14:49:28Z,Jim Frazer
8,csctracker-ai-core 26.15.2,A robust library to integrate Google Gemini AI...,A required part of this site couldnt load. Thi...,2026-04-08T14:49:18Z,None
9,Bain Capital's data center unit removes disgra...,Megaspeed gets final nail in its coffin after ...,Bain Capital's Bridge Data Centers (BDC) has t...,2026-04-08T14:47:54Z,"ashilov@gmail.com (Anton Shilov) , Anton Shilov"
10,clawed 4.8.2026.3,"Your AI co-teacher. Generate lessons, games, s...",A required part of this site couldnt load. Thi...,2026-04-08T14:46:54Z,None
11,ai-iq 5.8.0,Give your AI long-term memory in 1 command. SQ...,A required part of this site couldnt load. Thi...,2026-04-08T14:46:19Z,kobie@pop.co.za
12,Microsoft Abruptly Terminates VeraCrypt Accoun...,"Updates to VeraCrypt, a popular and long-runni...",Microsoft has terminated an account associated...,2026-04-08T14:46:15Z,Joseph Cox
13,Bitcoin Over $100K 'Totally Reasonable In One ...,"Bitcoin could return above $100,000 in the sho...",Benzinga and Yahoo Finance LLC may earn commis...,2026-04-08T14:46:07Z,David Okoya
14,OpenAI and Meaghan B Murphy Discuss How Famili...,"Nationwide media tour conducted by OpenAI, pro...","NEW YORK, April 08, 2026 (GLOBE NEWSWIRE) -- \...",2026-04-08T14:46:00Z,D S Simon
15,The Testaments: female friendship fuels resist...,The Testaments has to resolve the plot dilemma...,"The Testaments, now streaming on Disney+, has ...",2026-04-08T14:45:45Z,"Debra Ferreday, Senior Lecturer in Sociology, ..."
16,地上波で美女のマ●毛を集めて枕を作る企画を放送してしまい炎上,1 ：それでも動く名無し：2026/04/07(火) 19:24:03.22 ID:7BY6...,9 2026/04/07() 19:25:25.12 ID:r2LXnoOe0.net\r\...,2026-04-08T14:45:43Z,michaelsan
17,"CSS Studio: Design Visually, Ship Code with AI","CSS Studio: Design Visually, Ship Code with AI...",CSS Studio is a browser-based CSS design tool ...,2026-04-08T14:44:15Z,alex
18,Microsoft calls time on ASP.NET Core 2.3 on .N...,Tangled tale nears end as Redmond classifies i...,Microsoft has set an end-of-support date of Ap...,2026-04-08T14:43:32Z,Tim Anderson
19,sovyx 0.5.10,Sovereign Minds Engine — Persistent AI compani...,A required part of this site couldnt load. Thi...,2026-04-08T14:43:24Z,guipe@sovyx.ai
20,Trump Administration Pushes for Companies to B...,The frustrating experience of trying to speak ...,Skip to comments.\r\nTrump Administration Push...,2026-04-08T14:43:14Z,AMAC
21,Biggest problem with the MacBook Neo? It’s too...,Apple has a problem that other companies can o...,Apple has a problem with the MacBook Neo that ...,2026-04-08T14:42:51Z,Ed Hardy
22,Frontiers | State of health estimation method ...,As the main power source of new energy vehicle...,Abstract\r\nAs the main power source of new en...,2026-04-08T14:41:56Z,Jun Zhu
23,docc-ai 0.0.7,Python bindings and MLIR conversion for JIT co...,The MLIR module contains a dialect and transla...,2026-04-08T14:41:54Z,hello@daisytuner.com
24,WATCH: The impact of space travel on the human...,Space medicine researcher Dr. Farhan Asrar dis...,<ul><li>Trump achieved 'decisive military vict...,2026-04-08T14:40:55Z,ABC News
25,Why is the US stock market today Dow S&P 500 N...,"US stock market today surged sharply, with the...",US stock market today is rallying sharply as a...,2026-04-08T14:40:01Z,Piyush Shukla
26,Energous (WATT) Gained from a Dilutive Capital...,"Kingdom Capital Advisors, a registered investm...","Kingdom Capital Advisors, a registered investm...",2026-04-08T14:39:41Z,Soumya Eswaran
27,warden-ai 1.5.1,AI Agent Governance Scanner — local-only CLI t...,A required part of this site couldnt load. Thi...,2026-04-08T14:39:32Z,security@sharkrouter.ai
28,Deloitte launches quantum tech facility at IIT...,Deloitte India has launched a new quantum tech...,Deloitte India on Wednesday announced the laun...,2026-04-08T14:39:30Z,PTI
29,GMH Hotels: Is $7 Billion in Hotel Points a Pr...,"On this week’s ⁠Good Morning Hospitality, A Sk...","On this weeks Good Morning Hospitality, A Skif...",2026-04-08T14:39:00Z,Sarah Dandashy and Steve Turk
30,csctracker-ai-core 26.15.1,A robust library to integrate Google Gemini AI...,A required part of this site couldnt load. Thi...,2026-04-08T14:37:55Z,None
31,Show HN: Hoeren – Local-only meeting transcrip...,My company has a strict data policy around cal...,My company has a strict data policy around cal...,2026-04-08T14:37:24Z,dimaberlin
32,zenml 0.94.2,ZenML: MLOps for Reliable AI: from Classical A...,A required part of this site couldnt load. Thi...,2026-04-08T14:36:36Z,info@zenml.io
33,The Miniature Wife was an exercise in visual t...,"In Manuel Gonzales' 2013 short story ""The Mini...",<ul><li></li><li></li><li></li></ul>\r\nThe Mi...,2026-04-08T14:36:07Z,Charles Pulliam-Moore
34,hana-ai 1.1.26040800,Generative AI Toolkit for SAP HANA Cloud,A required part of this site couldnt load. Thi...,2026-04-08T14:36:01Z,None
35,codereviewbuddy 0.37.0,codereview buddy helps your AI agent interact ...,A required part of this site couldnt load. Thi...,2026-04-08T14:35:48Z,ismart@gmail.com
36,Anthropic Just Handed Apache $1.5M to Secure t...,Apache Software Foundation's Ruth Suehle says ...,Anthropic has handed the Apache Software Found...,2026-04-08T14:35:47Z,Sourav Rudra
37,How Ford Is Reinventing Itself as an AI Infras...,Ford (NYSE: F) closed 2025 with a $10.70 billi...,<ul><li>Ford (F) took a $10.70 billion impairm...,2026-04-08T14:35:21Z,Trey Thoelcke
38,Kingdom Capital Advisors’ Investment Thesis fo...,"Kingdom Capital Advisors, a registered investm...","Kingdom Capital Advisors, a registered investm...",2026-04-08T14:35:17Z,Soumya Eswaran
39,agentmark-pydantic-ai-v0 0.1.1,Pydantic AI adapter for AgentMark - integrate ...,A required part of this site couldnt load. Thi...,2026-04-08T14:34:52Z,None
40,E-retail set to cross $170 billion by 2030; q-...,India's e-retail market is projected to exceed...,Indias e-retail market is poised for its next ...,2026-04-08T14:34:13Z,BL Bengaluru Bureau
41,Show HN: Go-Bt: Minimalist Behavior Trees for Go,Minimalist BT implementation in Go. Contribute...,go-bt is a Behavior Tree library for Go.\r\nDe...,2026-04-08T14:33:30Z,rvitorper
42,Cybersecurity Stocks Climb Amid Anthropic's Pr...,Cybersecurity Stocks Climb Amid Anthropic's Pr...,The Fine Print: The following comments are own...,2026-04-08T14:33:18Z,feedfeeder
43,Nectar Social and Reddit Announce Strategic Da...,This partnership brings Reddit’s authentic com...,This partnership brings Reddits authentic comm...,2026-04-08T14:33:03Z,Business Wire
44,orbis-sdk added to PyPI,Python SDK for the Orbis API Marketplace — cal...,The official Python SDK for Orbis API Marketpl...,2026-04-08T14:32:32Z,None
45,peek-mcp 0.2.2,"Let AI agents see your UI — point at elements,...",A required part of this site couldnt load. Thi...,2026-04-08T14:31:13Z,None
46,Calero Launches Calero ConnectIQ,"Calero has launched Calero ConnectIQ, a new or...","ROCHESTER, N.Y., April 08, 2026 (GLOBE NEWSWIR...",2026-04-08T14:30:00Z,Calero
47,Electronic Design Automation (EDA) Market Size...,"Electronic Design Automation Market Size, Shar...","Austin, April 08, 2026 (GLOBE NEWSWIRE) -- Ele...",2026-04-08T14:30:00Z,SNS Insider pvt ltd
48,Humanoid Robot Market Set for Rapid Expansion:...,"Delray Beach, FL, April 08, 2026 (GLOBE NEWSWI...","Delray Beach, FL, April 08, 2026 (GLOBE NEWSWI...",2026-04-08T14:30:00Z,MarketsandMarkets Research Pvt. Ltd.
49,Conference organising in 2026 - QuirksBlog,The conference circuit is in a slump these day...,If you've been following any conference organi...,2026-04-08T14:27:13Z,None

In [ ]:
df = df.dropna(subset=["title"])
df["description"] = df["description"].fillna("")
df.drop_duplicates(subset="title")

,title,description,content,publishedAt,author
0,Nutanix signals an infrastructure shift in AI ...,As “move fast” collides headfirst with “don’t ...,As “move fast” collides headfirst with “don’t ...,2026-04-08T14:55:07Z,Emile Louw
1,"China is going after fake expert influencers, ...",China issued new regulation banning people wit...,Do you get health tips on social media? Maybe ...,2026-04-08T14:53:25Z,Catherina Gioino
2,Faybl Brand Identity: Fubo Studio Designs AI f...,Faybl Brand Identity: Fubo Studio Designs AI f...,Fubo Studio crafts the Faybl brand identity ar...,2026-04-08T14:53:00Z,alex
3,OpenAI puts ‘Stargate UK’ on hold in blow to B...,OpenAI said issues including the U.K.'s copyri...,"The sites included Cobalt Park, part of a gove...",2026-04-08T14:52:33Z,Joseph Bambridge
4,"What’s up with… Gamma Comms, Globe, DT",Gamma Comms confirms takeover talksGlobe joins...,In today’s industry news roundup: UK’s Gamma’s...,2026-04-08T14:51:26Z,TelecomTV Staff
...,...,...,...,...,...
95,Supermicro launches probe after staff charged ...,Board-led inquiry follows indictment of two em...,Supermicro has launched an independent investi...,2026-04-08T14:15:35Z,Dan Robinson
96,"Omnia Sol, glitch artist and cinematic raver","Syd Ross resists tidy categorization, but as a...",Omnia Sol performs with Chicago A/V collective...,2026-04-08T14:15:34Z,Micco Caporale
97,"As IBS 2026 Approaches, LEPAS Unfolds Its “Ele...","WUHU, China, April 08, 2026 (GLOBE NEWSWIRE) —...","WUHU, China, April 08, 2026 (GLOBE NEWSWIRE) T...",2026-04-08T14:15:27Z,GlobeNewswire
98,Mobile Virtual Network Operator (MVNO) Market ...,Emerging MVNO market opportunities include lev...,"Dublin, April 08, 2026 (GLOBE NEWSWIRE) -- The...",2026-04-08T14:15:00Z,Research and Markets
99,INVESTOR ALERT: Class Action Lawsuit Filed on ...,"ATLANTA, April 08, 2026 (GLOBE NEWSWIRE) -- A ...","ATLANTA, April 08, 2026 (GLOBE NEWSWIRE) -- A ...",2026-04-08T14:14:00Z,Holzer & Holzer

In [ ]:
df["publishedAt"] = pd.to_datetime(df["publishedAt"], errors="coerce")
df.head()

,title,description,content,publishedAt,author
0,Nutanix signals an infrastructure shift in AI ...,As “move fast” collides headfirst with “don’t ...,As “move fast” collides headfirst with “don’t ...,2026-04-08 14:55:07+00:00,Emile Louw
1,"China is going after fake expert influencers, ...",China issued new regulation banning people wit...,Do you get health tips on social media? Maybe ...,2026-04-08 14:53:25+00:00,Catherina Gioino
2,Faybl Brand Identity: Fubo Studio Designs AI f...,Faybl Brand Identity: Fubo Studio Designs AI f...,Fubo Studio crafts the Faybl brand identity ar...,2026-04-08 14:53:00+00:00,alex
3,OpenAI puts ‘Stargate UK’ on hold in blow to B...,OpenAI said issues including the U.K.'s copyri...,"The sites included Cobalt Park, part of a gove...",2026-04-08 14:52:33+00:00,Joseph Bambridge
4,"What’s up with… Gamma Comms, Globe, DT",Gamma Comms confirms takeover talksGlobe joins...,In today’s industry news roundup: UK’s Gamma’s...,2026-04-08 14:51:26+00:00,TelecomTV Staff

In [ ]:
df["full_text"] = df["title"] + " " + df["description"]
df.head()

,title,description,content,publishedAt,author,full_text
0,Nutanix signals an infrastructure shift in AI ...,As “move fast” collides headfirst with “don’t ...,As “move fast” collides headfirst with “don’t ...,2026-04-08 14:55:07+00:00,Emile Louw,Nutanix signals an infrastructure shift in AI ...
1,"China is going after fake expert influencers, ...",China issued new regulation banning people wit...,Do you get health tips on social media? Maybe ...,2026-04-08 14:53:25+00:00,Catherina Gioino,"China is going after fake expert influencers, ..."
2,Faybl Brand Identity: Fubo Studio Designs AI f...,Faybl Brand Identity: Fubo Studio Designs AI f...,Fubo Studio crafts the Faybl brand identity ar...,2026-04-08 14:53:00+00:00,alex,Faybl Brand Identity: Fubo Studio Designs AI f...
3,OpenAI puts ‘Stargate UK’ on hold in blow to B...,OpenAI said issues including the U.K.'s copyri...,"The sites included Cobalt Park, part of a gove...",2026-04-08 14:52:33+00:00,Joseph Bambridge,OpenAI puts ‘Stargate UK’ on hold in blow to B...
4,"What’s up with… Gamma Comms, Globe, DT",Gamma Comms confirms takeover talksGlobe joins...,In today’s industry news roundup: UK’s Gamma’s...,2026-04-08 14:51:26+00:00,TelecomTV Staff,"What’s up with… Gamma Comms, Globe, DT Gamma C..."

In [ ]:
positive_words = ["good", "growth", "profit", "rise", "success", "gain"]
negative_words = ["loss", "fall", "crash", "fraud", "decline", "drop"]

In [ ]:
def get_sentiment(text):
    pos = sum(word in text for word in positive_words)
    neg = sum(word in text for word in negative_words)

    score = pos - neg

    if score > 0:
        return "positive", score
    elif score < 0:
        return "negative", score
    else:
        return "neutral", score

In [ ]:
df[["sentiment", "score"]] = df["full_text"].apply(
    lambda x: pd.Series(get_sentiment(x))
)

In [ ]:
df[["title", "sentiment", "score"]].head(50)

                                                title sentiment  score
0   Nutanix signals an infrastructure shift in AI ...  positive      1
1   China is going after fake expert influencers, ...   neutral      0
2   Faybl Brand Identity: Fubo Studio Designs AI f...   neutral      0
3   OpenAI puts ‘Stargate UK’ on hold in blow to B...   neutral      0
4              What’s up with… Gamma Comms, Globe, DT   neutral      0
5   "Raptor Lake will continue to be abundantly av...   neutral      0
6                                   encypher-ai 3.1.0   neutral      0
7   Decision Latency: The Hidden Cost in Modern Su...   neutral      0
8                          csctracker-ai-core 26.15.2   neutral      0
9   Bain Capital's data center unit removes disgra...   neutral      0
10                                  clawed 4.8.2026.3   neutral      0
11                                        ai-iq 5.8.0   neutral      0
12  Microsoft Abruptly Terminates VeraCrypt Accoun...   neutral      0
13  Bitcoin Over $100K 'Totally Reasonable In One ...   neutral      0
14  OpenAI and Meaghan B Murphy Discuss How Famili...   neutral      0
15  The Testaments: female friendship fuels resist...   neutral      0
16                     地上波で美女のマ●毛を集めて枕を作る企画を放送してしまい炎上   neutral      0
17     CSS Studio: Design Visually, Ship Code with AI   neutral      0
18  Microsoft calls time on ASP.NET Core 2.3 on .N...   neutral      0
19                                       sovyx 0.5.10   neutral      0
20  Trump Administration Pushes for Companies to B...   neutral      0
21  Biggest problem with the MacBook Neo? It’s too...   neutral      0
22  Frontiers | State of health estimation method ...   neutral      0
23                                      docc-ai 0.0.7   neutral      0
24  WATCH: The impact of space travel on the human...   neutral      0
25  Why is the US stock market today Dow S&P 500 N...  positive      1
26  Energous (WATT) Gained from a Dilutive Capital...   neutral      0
27                                    warden-ai 1.5.1   neutral      0
28  Deloitte launches quantum tech facility at IIT...   neutral      0
29  GMH Hotels: Is $7 Billion in Hotel Points a Pr...   neutral      0
30                         csctracker-ai-core 26.15.1   neutral      0
31  Show HN: Hoeren – Local-only meeting transcrip...   neutral      0
32                                       zenml 0.94.2   neutral      0
33  The Miniature Wife was an exercise in visual t...   neutral      0
34                               hana-ai 1.1.26040800   neutral      0
35                             codereviewbuddy 0.37.0   neutral      0
36  Anthropic Just Handed Apache $1.5M to Secure t...   neutral      0
37  How Ford Is Reinventing Itself as an AI Infras...   neutral      0
38  Kingdom Capital Advisors’ Investment Thesis fo...   neutral      0
39                     agentmark-pydantic-ai-v0 0.1.1   neutral      0
40  E-retail set to cross $170 billion by 2030; q-...  positive      1
41   Show HN: Go-Bt: Minimalist Behavior Trees for Go   neutral      0
42  Cybersecurity Stocks Climb Amid Anthropic's Pr...   neutral      0
43  Nectar Social and Reddit Announce Strategic Da...   neutral      0
44                            orbis-sdk added to PyPI   neutral      0
45                                     peek-mcp 0.2.2   neutral      0
46                   Calero Launches Calero ConnectIQ   neutral      0
47  Electronic Design Automation (EDA) Market Size...   neutral      0
48  Humanoid Robot Market Set for Rapid Expansion:...  positive      1
49         Conference organising in 2026 - QuirksBlog  positive      1

In [ ]:
df.to_csv("news_sentiment.csv", index=False)
from google.colab import files
files.download("news_sentiment.csv")